services:
  accountsdb:
    image: "mysql"
    container_name: "accountsdb"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "accountsdb"
    networks:
      - easyBank_db
  cardsdb:
    image: "mysql"
    container_name: "cardsdb"
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cardsdb"
    networks:
      - easyBank_db
  loansdb:
    image: "mysql"
    container_name: "loansdb"
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "loansdb"
    networks:
      - easyBank_db
  configserver:
    image: "sdocker001/configserver:latest"
    container_name: configserver_ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easyBank
  accounts:
    image: "sdocker001/accounts:latest"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easyBank
      - easyBank_db
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
  loans:
    image: "sdocker001/loans:latest"
    container_name: loans_ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easyBank
      - easyBank_db
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
  cards:
    image: "sdocker001/cards:latest"
    container_name: cards_ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easyBank
      - easyBank_db
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
networks:
  easyBank:
    driver: "bridge"
  easyBank_db:
    driver: "bridge"