services:
  accounts:
    image: "microservice/accounts:latest"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easyBank
  loans:
    image: "microservice/loans:latest"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easyBank
  cards:
    image: "microservice/cards:latest"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easyBank
networks:
  easyBank:
    driver: "bridge"