server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sdcode001/spring-cloud-config-demo-repo.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        # native:
          # search-location: "classpath:/config"
          # search-location: "file:////Users//souvik-dey-mac//Documents//Learning//Microservices//spring_cloud_config_demo//config_dir"
  rabbitmq:
    host: "127.0.0.1"
    port: "5672"
    username: "guest"
    password: "guest"

encrypt:
  key: "66acec88fd4c2f251f254c7c6f199539"

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
